version: 2.1

jobs:
  fail_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo "didnt fail"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - fail_job