version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file file://template.yml \
              --parameters file://template-params.json \
              --stack-name my-stack
workflows:
  my_workflow:
    jobs:
      - create_infrastructure