# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
workflows:
  test-env-vars:
    jobs:
      - build
      - save_hello_world_output
      - print_output_file

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo variable with my name"
          command: |
            echo $VARDAS
  save_hello_world_output:
    build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - persist_to_workspace:
            root: /tmp/dir
        - run:
            name: "save hello world output"
            command: |
              echo "hello world" > output.txt
  print_output_file:
    build:
      docker:
        - image: cimg/base:2020.01
      steps:
        - checkout
        - attach_workspace:
            at: /tmp/dir
        - run:
            name: "print output file"
            command: |
              cat /tmp/dir/output.txt
